directories:
  output: dist-electron
  buildResources: build
appId: com.superapp.app
productName: SuperApp
files:
  - filter:
      - dist/**/*
      - electron/**/*
win:
  target:
    - portable
electronVersion: 22.0.0
